const ACTIONS = {
  FETCH_WEATHER_DATA: 'FETCH_WEATHER_DATA',
  FETCH_WEATHER_ERROR: 'FETCH_WEATHER_ERROR',
  DISPLAY_GEOLOCATION_NOT_AVAILABLE: 'DISPLAY_GEOLOCATION_NOT_AVAILABLE',
  GO_TO_PREV_PAGE: 'GO_TO_PREV_PAGE',
  GO_TO_NEXT_PAGE: 'GO_TO_NEXT_PAGE'
};

export default ACTIONS;
